name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: waka-box
        uses: matchai/waka-box@v5.0.0
        env:
          GH_TOKEN: ${{ vars.GH_TOKEN }}
          GIST_ID: ${{ vars.GIST_ID }}
          WAKATIME_API_KEY: ${{ vars.WAKATIME_API_KEY }}
